### ISSUE TITLE
Styling improvement

### ISSUE THREAD

**Issue by abdullah-asghar-khan** [ademibowale/Leader-Board#6]
Great job! 👍 
Your project is working fine, here I have some optional suggestions for you :

- Styling improvement to make the project more visible.

**Comment by chimwemwe007** [comment]
- Kindly personalise your README.md  file, this makes it easier yo find your profiles on LinkedIn, twitter and github.
- I would suggest that you refrain from using keywords in your js file the 'filter' keyword to create a finction. This might cause unforeseen circumstances. According to javascript best practices.

**Comment by ademibowale** [comment]
@chimwemwe007  Great job , thank you and i will amend all

**Comment by ademibowale** [comment]
@Abdullah2213565 Thank you i will work on that
